FROM nginx:1.25-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf       /etc/nginx/nginx.conf
COPY protected.conf   /etc/nginx/protected.conf
COPY proxy-params.conf /etc/nginx/proxy-params.conf
EXPOSE 8000
CMD ["nginx", "-g", "daemon off;"]