"""uuid_migration_all_tables

Revision ID: 3e9d0ce09e7f
Revises: 
Create Date: 2026-03-16 14:42:47.387825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e9d0ce09e7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_published_at', 'courses', ['published_at'], unique=False)
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_index(op.f('ix_courses_status'), 'courses', ['status'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('dropped_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('enrollment_source', sa.String(length=100), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment_student_course')
    )
    op.create_index('idx_enrollments_enrolled_at', 'enrollments', ['enrolled_at'], unique=False)
    op.create_index('idx_enrollments_last_accessed', 'enrollments', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('verification_code', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('score_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('issued_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number'),
    sa.UniqueConstraint('enrollment_id'),
    sa.UniqueConstraint('verification_code')
    )
    op.create_index('idx_certificates_enrollment', 'certificates', ['enrollment_id'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'item_type', 'item_id', name='uq_progress_enrollment_item')
    )
    op.create_index(op.f('ix_progress_enrollment_id'), 'progress', ['enrollment_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'module_id', 'attempt_number', name='uq_quiz_attempts')
    )
    op.create_index(op.f('ix_quiz_attempts_enrollment_id'), 'quiz_attempts', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_module_id'), 'quiz_attempts', ['module_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_status'), 'quiz_attempts', ['status'], unique=False)
    op.create_table('user_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('user_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_quiz_attempt_id'), 'user_answers', ['quiz_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_answers_quiz_attempt_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_quiz_attempts_status'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_module_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_enrollment_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_progress_enrollment_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index('idx_certificates_enrollment', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index('idx_enrollments_last_accessed', table_name='enrollments')
    op.drop_index('idx_enrollments_enrolled_at', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_courses_status'), table_name='courses')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_index('idx_courses_published_at', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
